### PR TITLE
Upgrade yolov5 064365d8683fd002e9ad789c1e91fa3d021b44f0

### PR DESCRIPTION
**Pull request by ccssu**
#  [暂时不要合并]
做测试，分为性能测试和功能测试 
# 性能测试 
## 模型精度验证
- [x] yolov5s精度验证,https://github.com/Oneflow-Inc/one-yolov5/pull/111#issuecomment-1427015838
- [x] yolov5s-seg精度验证 https://github.com/Oneflow-Inc/one-yolov5/pull/111#issuecomment-1427209447
- [ ] yolov5s-cls 精度验证  <a href="#cls_ox01"> 未达标Test01</a>

## 速度显存测试

- [x] --bbox_iou_optim 优化添加
- [x] --multi_tensor_optimize 优化添加
- [x] fp32速度显存测试  https://github.com/Oneflow-Inc/one-yolov5/pull/111#issuecomment-1427223550

# 功能测试 

- [x] --resume , https://github.com/Oneflow-Inc/one-yolov5/pull/111#issuecomment-1427393607
- [x] --wandb 
- [x] 自动下载权重
- [x] hub  https://github.com/Oneflow-Inc/one-yolov5/pull/111#issuecomment-1430732648
- [ ] export.py 导出onnx 模块
- [x] predict.py ,  val.py 验证模块

### CODE REVIEW

**Comment by ccssu** [comment]
##  yolov5s 
- [x]  wandb 日志：https://wandb.ai/wearmheart/YOLOv5/runs/tnd1d0t3?workspace=user-wearmheart
- [x]  精度数据如下:

| 后端 |   metrics/mAP_0.5,|metrics/mAP_0.5:0.95,|
|---     |   ---|---|
| OneFlow |   37.659 |    56.992 |
|PyTorch | 37.4 | 56.8|

全部数据 [results.txt](https://github.com/Oneflow-Inc/one-yolov5/files/10694564/results.txt)
启动指令:
```shell 
python -m oneflow.distributed.launch --nproc_per_node 4  \ 
train.py --batch-size 128 --data coco.yaml --weights " " --cfg models/yolov5s.yaml --img 640 --epochs 300
```

**Comment by ccssu** [comment]
| 后端    | GPU | mAP_0.5:0.95(B) | mAP_0.5:0.95(M) | wandb 日志                                                                                                            |
| ------- | --- | --------------- | --------------- | --------------------------------------------------------------------------------------------------------------------- |
| OneFlow | 8   | 37.558          | 31.402          | [One-YOLOv5s-seg_v1.2.0](https://wandb.ai/wearmheart/YOLOv5-Segment/runs/tt8v7pnm/overview?workspace=user-wearmheart) |
| PyTorch | 1   | 37.705          | 31.651          | [YOLOV5s-seg](https://wandb.ai/glenn-jocher/YOLOv5_v70_official/runs/3difxxrr/overview?workspace=user-wearmheart)     |

OneFlow后端启动指令

```shell
python -m oneflow.distributed.launch --nproc_per_node  8  \
    segment/train.py \
    --data coco.yaml \
    --weights ' ' \
    --cfg yolov5s-seg.yaml   \
    --img 640  \
    --batch-size 320    \
    --epochs 300  \
    --bbox_iou_optim --multi_tensor_optimize 
```

**Comment by ccssu** [comment]
| 单卡    | amp   | epoch | gpu | batch | 数据集        | 模型            | time(min) | 显存    |
| ------- | ----- | ----- | --- | ----- | ------------- | --------------- | --------- |---|
| OneFlow | False | 1     | 1   | 8     | coco          | yolov5s-default | 18:49     | 4.282G  |
| PyTorch | False | 1     | 1   | 8     | coco          | yolov5s-default | 21:56     | 3.16G   |
| OneFlow | False | 1     | 1   | 16    | coco          | yolov5s-default | 14:34     | 7.813G  |
| PyTorch | False | 1     | 1   | 16    | coco          | yolov5s-default | 17:46     | 6.05G   |
| OneFlow | False | 1     | 1   | 8     | coco          | yolov5s-seg     | 25:36     | 6.108G  |
| PyTorch | False | 1     | 1   | 8     | coco          | yolov5s-seg     | 33:16     | 5.13G   |
| OneFlow | False | 1     | 1   | 16    | coco          | yolov5s-seg     | 24:07     | 10.683G |
| PyTorch | False | 1     | 1   | 16    | coco          | yolov5s-seg     | 29:55     | 8.98G   |
| OneFlow | False | 1     | 1   | 16    | coco          | yolov5s-seg     | 24:07     | 10.683G |
| PyTorch | False | 1     | 1   | 16    | coco          | yolov5s-seg     | 29:55     | 8.98G   |
| OneFlow | False | 100   | 1   | 64    | imagenette160 | yolov5s-cls     | 12.06     | 3.567G  |
| PyTorch | False | 100   | 1   | 64    | imagenette160 | yolov5s-cls     | 11:88     | 1.28G   |



`export NVIDIA_TF32_OVERRIDE=0` 

## 测试启动指令示例：
###  yolov5s-default：
<details open>
<summary>OneFlow后端</summary>

```shell
python  \
    train.py \
    --batch-size 8 \
    --data coco.yaml \
    --weights ' ' \
    --cfg models/yolov5s.yaml \
    --img 640 \
    --epochs 1  \
    --bbox_iou_optim --multi_tensor_optimize
```
</details>


<details open>
<summary>PyTorch后端</summary>

```shell
export NVIDIA_TF32_OVERRIDE=0 # 使用fp32
python  \
    train.py \
    --batch-size 16 \
    --data coco.yaml \
    --weights ' ' \
    --cfg models/yolov5s.yaml \
    --img 640 \
    --epochs 1  \
```
</details>


###  yolov5s-seg：
<details open>
<summary>OneFlow后端</summary>

```shell
python \
    segment/train.py \
    --data coco.yaml \
    --weights ' ' \
    --cfg  models/segment/yolov5s-seg.yaml \
    --img 640 \
    --batch-size 8
    --epochs 1 \
    --bbox_iou_optim --multi_tensor_optimize 
```
</details>


<details open>
<summary>PyTorch后端</summary>

```shell
export NVIDIA_TF32_OVERRIDE=0 # 使用fp32
python \
    segment/train.py \
    --data coco.yaml \
    --weights ' ' \
    --cfg  models/segment/yolov5s-seg.yaml \
    --img 640 \
    --epochs 1 \
    --batch-size 8
```
</details>

###  yolov5s-cls：
<details open>
<summary>OneFlow后端</summary>

```shell
python classify/train.py --model /home/fengwen/one-yolov5/runs/train/exp/weights/best.of \
--data ../datasets/classify/imagenette160  --multi_tensor_optimize \
--epochs 100  --img 224
```
</details>


<details open>
<summary>PyTorch后端</summary>

```shell
export NVIDIA_TF32_OVERRIDE=0 # 使用fp32

python classify/train.py --model /home/fengwen/yolov5/runs/train/exp11/weights/best.pt \
--data ../datasets/classify/imagenette160   \
--epochs 100 --img 224 
```
</details>

**Comment by ccssu** [comment]
如果您的训练进程中断了，可以通过 --resume augment 这样恢复先前的训练进程。

注意： 记得把 augment   替换为你要恢复训练的模型权重路径, 比如
--resume /path/to/your/checkpoint/path.of 
示例:
```shell 
python  \
    train.py \
    --batch-size 16 \
    --data coco128.yaml \
    --weights ' ' \
    --cfg models/yolov5s.yaml \
    --img 640 \
    --bbox_iou_optim --multi_tensor_optimize \
    --project test_resume
    --name default
    --resume /home/fengwen/one-yolov5/test_resume/default/weights/last.of
```

**Comment by ccssu** [comment]
image

**Comment by ccssu** [comment]
分类模型 精度验证
<details close>
<summary> yolov5s-cls 模型 opt.yaml</summary>

```
model: runs/yolov5s.of
data: /data/home/fengwen/datasets/imagenet
epochs: 90
batch_size: 256
imgsz: 224
nosave: false
cache: null
device: ''
workers: 8
project: One-YOLOv5_v_1_2_0_train
name: yolov5s-default
exist_ok: false
pretrained: true
optimizer: SGD
lr0: 0.1
decay: 5.0e-05
label_smoothing: 0.1
cutoff: null
dropout: null
verbose: false
seed: 0
local_rank: -1
multi_tensor_optimizer: true
save_dir: One-YOLOv5_v_1_2_0_train/yolov5s-default24
```
</details>


<details close>
<summary> results.csv 分类模型</summary>

```
                  epoch,             train/loss,               val/loss,  metrics/accuracy_top1,  metrics/accuracy_top5,                   lr/0
                      0,                 3.4587,                 2.9858,                0.50158,                0.76712,                 0.0989
                      1,                 2.7672,                 2.6174,                0.59452,                0.83316,                 0.0978
                      2,                 2.5984,                 2.4773,                0.62854,                 0.8566,                 0.0967
                      3,                 2.4937,                 2.4347,                0.63998,                0.86306,                 0.0956
                      4,                 2.4261,                 2.4115,                0.64562,                0.86682,                 0.0945
                      5,                 2.3782,                 2.3912,                 0.6509,                0.86886,                 0.0934
                      6,                 2.3441,                 2.3732,                0.65526,                0.87252,                 0.0923
                      7,                 2.3118,                 2.3567,                0.65944,                0.87658,                 0.0912
                      8,                 2.2871,                 2.3428,                0.66442,                0.87846,                 0.0901
                      9,                 2.2675,                 2.3313,                 0.6677,                0.87976,                  0.089
                     10,                 2.2474,                 2.3217,                0.67018,                0.88096,                 0.0879
                     11,                 2.2309,                 2.3132,                0.67268,                0.88172,                 0.0868
                     12,                 2.2149,                 2.3076,                0.67394,                0.88226,                 0.0857
                     13,                 2.2009,                 2.3012,                0.67576,                 0.8837,                 0.0846
                     14,                 2.1848,                  2.296,                0.67736,                0.88428,                 0.0835
                     15,                 2.1727,                 2.2921,                0.67876,                0.88484,                 0.0824
                     16,                 2.1588,                 2.2888,                 0.6791,                0.88638,                 0.0813
                     17,                  2.149,                 2.2872,                0.67914,                0.88618,                 0.0802
                     18,                 2.1382,                 2.2858,                0.67946,                 0.8862,                 0.0791
                     19,                   2.13,                  2.282,                0.68132,                0.88666,                  0.078
                     20,                 2.1164,                 2.2797,                0.68176,                0.88724,                 0.0769
                     21,                 2.1061,                 2.2784,                0.68194,                0.88778,                 0.0758
                     22,                 2.0967,                 2.2787,                 0.6823,                0.88764,                 0.0747
                     23,                 2.0892,                 2.2755,                0.68198,                0.88774,                 0.0736
                     24,                 2.0772,                 2.2753,                0.68292,                 0.8882,                 0.0725
                     25,                 2.0668,                 2.2732,                0.68328,                0.88832,                 0.0714
                     26,                 2.0579,                 2.2716,                 0.6841,                0.88876,                 0.0703
                     27,                 2.0504,                 2.2705,                0.68386,                0.88898,                 0.0692
                     28,                 2.0413,                 2.2712,                 0.6843,                0.88872,                 0.0681
                     29,                 2.0322,                 2.2705,                0.68452,                 0.8889,                  0.067
                     30,                  2.021,                 2.2697,                0.68476,                 0.8891,                 0.0659
                     31,                 2.0129,                 2.2702,                0.68546,                0.88936,                 0.0648
                     32,                 2.0042,                 2.2686,                 0.6849,                0.88918,                 0.0637
                     33,                 1.9938,                 2.2699,                0.68556,                 0.8884,                 0.0626
                     34,                  1.985,                   2.27,                 0.6853,                0.88824,                 0.0615
                     35,                  1.975,                 2.2707,                0.68548,                 0.8888,                 0.0604
                     36,                  1.963,                  2.272,                0.68602,                 0.8895,                 0.0593
                     37,                 1.9564,                 2.2736,                0.68518,                0.88898,                 0.0582
                     38,                 1.9457,                 2.2736,                0.68502,                0.88904,                 0.0571
                     39,                 1.9338,                 2.2751,                0.68466,                0.88806,                  0.056
                     40,                 1.9249,                 2.2782,                0.68418,                0.88774,                 0.0549
                     41,                 1.9148,                 2.2771,                 0.6839,                0.88784,                 0.0538
                     42,                 1.9067,                 2.2779,                0.68246,                0.88778,                 0.0527
                     43,                 1.8971,                 2.2787,                 0.6828,                 0.8885,                 0.0516
                     44,                 1.8861,                 2.2809,                0.68262,                0.88816,                 0.0505
                     45,                 1.8722,                 2.2819,                  0.683,                0.88756,                 0.0494
                     46,                 1.8648,                 2.2847,                0.68326,                 0.8879,                 0.0483
                     47,                 1.8533,                 2.2858,                 0.6819,                0.88868,                 0.0472
                     48,                 1.8414,                 2.2881,                0.68144,                0.88778,                 0.0461
                     49,                 1.8324,                 2.2905,                0.68098,                0.88708,                  0.045
                     50,                 1.8175,                  2.293,                0.68048,                  0.887,                 0.0439
                     51,                 1.8062,                 2.2975,                0.68028,                0.88666,                 0.0428
                     52,                 1.7972,                 2.3034,                0.67998,                0.88622,                 0.0417
                     53,                 1.7821,                  2.305,                0.67928,                0.88596,                 0.0406
                     54,                 1.7735,                 2.3074,                0.67742,                0.88528,                 0.0395
                     55,                  1.757,                 2.3102,                0.67756,                 0.8852,                 0.0384
                     56,                 1.7472,                 2.3137,                0.67674,                 0.8851,                 0.0373
                     57,                 1.7324,                 2.3177,                0.67568,                0.88478,                 0.0362
                     58,                 1.7195,                 2.3227,                0.67542,                0.88394,                 0.0351
                     59,                 1.7059,                 2.3279,                0.67484,                0.88344,                  0.034
                     60,                 1.6916,                 2.3306,                0.67392,                0.88262,                 0.0329
                     61,                 1.6777,                 2.3381,                0.67194,                0.88168,                 0.0318
                     62,                 1.6627,                 2.3432,                 0.6711,                0.88136,                 0.0307
                     63,                 1.6482,                 2.3474,                0.67086,                0.88008,                 0.0296
                     64,                 1.6326,                  2.354,                0.66968,                0.87968,                 0.0285
                     65,                 1.6153,                 2.3597,                0.66776,                0.87884,                 0.0274
                     66,                 1.6018,                 2.3673,                0.66702,                0.87814,                 0.0263
                     67,                 1.5838,                 2.3745,                0.66526,                 0.8775,                 0.0252
                     68,                 1.5672,                 2.3801,                0.66344,                0.87644,                 0.0241
                     69,                 1.5505,                 2.3869,                0.66252,                0.87594,                  0.023
                     70,                 1.5331,                 2.3942,                0.66124,                 0.8758,                 0.0219
                     71,                  1.515,                 2.4002,                0.66024,                0.87438,                 0.0208
                     72,                 1.4949,                 2.4091,                0.65824,                0.87302,                 0.0197
                     73,                 1.4769,                 2.4169,                0.65758,                0.87252,                 0.0186
                     74,                 1.4573,                 2.4258,                0.65602,                0.87128,                 0.0175
                     75,                 1.4382,                 2.4345,                0.65456,                0.86968,                 0.0164
                     76,                 1.4171,                 2.4442,                0.65298,                0.86816,                 0.0153
                     77,                 1.3982,                  2.454,                0.65118,                0.86654,                 0.0142
                     78,                 1.3773,                 2.4655,                0.64912,                 0.8654,                 0.0131
                     79,                 1.3576,                 2.4744,                0.64684,                0.86466,                  0.012
                     80,                 1.3371,                  2.485,                0.64502,                0.86316,                 0.0109
                     81,                 1.3175,                  2.496,                0.64302,                0.86224,                 0.0098
                     82,                 1.2983,                 2.5091,                0.64076,                0.86028,                 0.0087
                     83,                 1.2802,                 2.5188,                0.63894,                0.85916,                 0.0076
                     84,                 1.2626,                 2.5296,                 0.6368,                 0.8571,                 0.0065
                     85,                 1.2472,                  2.541,                0.63486,                0.85536,                 0.0054
                     86,                 1.2327,                 2.5533,                0.63326,                0.85334,                 0.0043
                     87,                 1.2193,                 2.5659,                0.63124,                 0.8523,                 0.0032
                     88,                 1.2083,                  2.577,                0.63018,                0.85058,                 0.0021
                     89,                 1.1983,                 2.5891,                0.62896,                0.84954,                  0.001

```
</details>

**Comment by BBuf** [comment]
> 后端 	GPU 	mAP_0.5:0.95(B) 	mAP_0.5:0.95(M) 	wandb 日志
> OneFlow 	8 	37.558 	31.402 	[One-YOLOv5s-seg_v1.2.0](https://wandb.ai/wearmheart/YOLOv5-Segment/runs/tt8v7pnm/overview?workspace=user-wearmheart)
> PyTorch 	1 	37.705 	31.651 	[YOLOV5s-seg](https://wandb.ai/glenn-jocher/YOLOv5_v70_official/runs/3difxxrr/overview?workspace=user-wearmheart)
> 
> OneFlow后端启动指令
> 
> ```shell
> python -m oneflow.distributed.launch --nproc_per_node  8  \
>     segment/train.py \
>     --data coco.yaml \
>     --weights ' ' \
>     --cfg yolov5s-seg.yaml   \
>     --img 640  \
>     --batch-size 320    \
>     --device 0,1,2,4      \
>     --epochs 300  \
>     --bbox_iou_optim --multi_tensor_optimize 
> ```

这个segment的功能并不是我理解的用来做语义分割的么？还是做检测任务吗

**Comment by BBuf** [comment]
> > 后端 	GPU 	mAP_0.5:0.95(B) 	mAP_0.5:0.95(M) 	wandb 日志
> > OneFlow 	8 	37.558 	31.402 	[One-YOLOv5s-seg_v1.2.0](https://wandb.ai/wearmheart/YOLOv5-Segment/runs/tt8v7pnm/overview?workspace=user-wearmheart)
> > PyTorch 	1 	37.705 	31.651 	[YOLOV5s-seg](https://wandb.ai/glenn-jocher/YOLOv5_v70_official/runs/3difxxrr/overview?workspace=user-wearmheart)
> > OneFlow后端启动指令
> > ```shell
> > python -m oneflow.distributed.launch --nproc_per_node  8  \
> >     segment/train.py \
> >     --data coco.yaml \
> >     --weights ' ' \
> >     --cfg yolov5s-seg.yaml   \
> >     --img 640  \
> >     --batch-size 320    \
> >     --device 0,1,2,4      \
> >     --epochs 300  \
> >     --bbox_iou_optim --multi_tensor_optimize 
> > ```
> 
> 这个segment的功能并不是我理解的用来做语义分割的么？还是做检测任务吗

这里确认是全景分割。类似于mask-rcnn

**Review by BBuf — APPROVED** [review]

**Pull request merged**
